version: "3.7"

services:
  node_one:
    container_name: node_one
    build: ./
    expose:
      - "6379"
      - "26379"
    links:
      - node_two
      - node_three
    volumes:
      - ./config:/config
    command: sh -c "redis-server /config/redis_node_one.conf &&\
                    redis-server /config/sentinel_node_one.conf - sentinel"

  node_two:
    container_name: node_two
    build: ./
    expose:
      - "6380"
      - "26380"
    volumes:
      - ./config:/config

  node_three:
    container_name: node_three
    build: ./
    expose:
      - "6381"
      - "26381"
    volumes:
      - ./config:/config
